### ISSUE TITLE
Volume for `fpm` points to an incorrect path to `config.ini`

### ISSUE THREAD

**Issue by vireshpatel** [catchdigital/drucker#10]
`fpm` volume points to `./docker/etc/php/config.ini` which doesn't match with the other config paths; needs to point be `./etc/php/config.ini`.

https://github.com/catchdigital/drucker/blob/23e5e8c4ef039985b48e70a14982c48138cadd8b/docker-compose.yml#L30

**Comment by alberto115** [comment]
PR merged on tag 2.6.0
