### ISSUE TITLE
Up'ing FastCGI Buffer sizes

### ISSUE THREAD

**Issue by vireshpatel** [catchdigital/drucker#7]
File: `/src/master/etc/nginx/conf.d/default.conf`

Some Drupal admin pages throw 502 errors on screen whilst it reports in the logs: `... *243 upstream sent too big header while reading response header from upstream...`

This is due to the buffer sizes and needs increasing to the following: 
```
fastcgi_buffers 16 32k;
fastcgi_buffer_size 64k;
`````

**Comment by alberto115** [comment]
PR merged on tag 2.6.0
